/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"


double
rand_prog_1(char *host1, char *host2, char *host3)
{
	CLIENT *clnt1;
  CLIENT *clnt2;
  CLIENT *clnt3;
  
	void  *result_1;
	long  initialize_random_1_arg;
	double  *result_2;
	char *get_next_random_1_arg;
  double l, m;
  l = 0.0;
  m = 0.0;
  double *temp_1 = &l;
  double *temp_2 = &m;

#ifndef	DEBUG
	clnt1 = clnt_create (host1, RAND_PROG, RAND_VERS, "udp");
	if (clnt1 == NULL) {
		clnt_pcreateerror (host1);
		exit (1);
	}
  
  clnt2 = clnt_create (host2, RAND_PROG, RAND_VERS, "udp");
	if (clnt2 == NULL) {
		clnt_pcreateerror (host2);
		exit (1);
	}
  
  clnt3 = clnt_create (host3, RAND_PROG, RAND_VERS, "udp");
	if (clnt3 == NULL) {
		clnt_pcreateerror (host3);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = initialize_random_1(&initialize_random_1_arg, clnt1);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt1, "call failed");
	}
  
	result_1 = initialize_random_1(&initialize_random_1_arg, clnt2);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt2, "call failed");
	}
  
  result_1 = initialize_random_1(&initialize_random_1_arg, clnt3);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt3, "call failed");
	}
  
  //not quite fully parallel because the client doesn't store earlier results
  //so instead what's happening is that server1 generates a random number by itself
	temp_1 = get_next_random_1((void*)&get_next_random_1_arg, clnt1, temp_1, temp_2);
	if (temp_1 == (double *) NULL) {
		clnt_perror (clnt2, "call failed");
	}
  
  //server 2 generates a number from the results of server 1 and itself
  temp_2 = get_next_random_1((void*)&get_next_random_1_arg, clnt2, temp_1, temp_2);
	if (temp_2 == (double *) NULL) {
		clnt_perror (clnt3, "call failed");
	}
  
  //and server three generates a number from server 1, 2, and itself
  result_2 = get_next_random_1((void*)&get_next_random_1_arg, clnt3, temp_1, temp_2);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt3, "call failed");
	}
  
  
#ifndef	DEBUG
	clnt_destroy (clnt1);
  clnt_destroy (clnt2);
  clnt_destroy (clnt3);
#endif	 /* DEBUG */

  return *result_2;
}


int
main (int argc, char *argv[])
{
	char *host1;
  char *host2;
  char *host3;

	if (argc != 4) {
    //client needs to connect to three servers
		printf ("usage: %s server1 server2 server3\n", argv[0]);
		exit (1);
	}
	host1 = argv[1];
  host2 = argv[2];
  host3 = argv[3];
  
	rand_prog_1 (host1, host2, host3);

  double x;
      int i;
      printf("\n twenty random numbers ");
      for ( i = 0; i < 20; ++i ){
              x = rand_prog_1 (host1, host2, host3);
              printf(" %f, ", x );
      }
exit (0);
}
