/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>


void *
initialize_random_1_svc(long *argp, struct svc_req *rqstp)
{
  static char * result;
  struct timeval tv;
  
  for (int i = 0; i < 500000; i++){
    i++;
    i--; //doing nothing to stall for time
  }
  gettimeofday(&tv, NULL);
  time_t current_time = tv.tv_sec;
  srand((unsigned) current_time);

  return (void *) &result;
}

double *
get_next_random_1_svc(void *argp, struct svc_req *rqstp)
{
  static double  result;

  result = (double)rand()/RAND_MAX*1.0;

  return &result;
}
